### ISSUE TITLE
GUI not launching after updating DPEdit binaries 

### ISSUE THREAD

**Issue by silvia95guy** [programmer2514/DPEdit-GUI#2]
Downloaded and installed, with the GUI opening, but after updating the DPEdit binary's the GUI hangs and will not open. Thought it might be an issues with Python, since I had different python versions, so I deleted all of them, and had the .exe install the python dependency version it needed, but still hangs. Any idea what to do to rectify the issue?

**Comment by programmer2514** [comment]
I cannot seem to reproduce this behavior on my device.
Have you tried running the standalone [DPEdit](https://github.com/programmer2514/DPEdit/releases/latest) command line utility from the console to ensure that it functions properly?
If not, you may need to re-install/repair the latest [Visual C++ Redistributables](https://aka.ms/vs/17/release/vc_redist.x64.exe).
If that works fine but the GUI still hangs, let me know and I will investigate further.

**Comment by rdlugosz** [comment]
**update: see my next comment; the fix for me was uninstalling Parsec** 

I'm seeing the same behavior. Using the cmd line tool now, which works great, but thought I'd post some findings here in case it's helpful.

* My GUI worked fine several months ago (quite possibly before any of the virtual displays below were added...)
* Now it won't start - shows an initial window (but without any of the actual gui controls - just a frame w white background) & spins until you kill it
* Cmd line dpedit tool works without issue
* A dpedit.exe \L shows that I've got a ton of virtual displays. I'll list them below, but mostly they are inactive virtual displays. (FWIW, my current setup has two physical monitors connected.)

My gut is that it's got something to do with the large number of virtual displays all sitting at the same position breaking something in the gui code, but that's just a guess. Hope this info is helpful.

```
C:\Users\ryan\Downloads>dpedit.exe /L

Display #1
Device name: \\.\DISPLAY1
Device string: NVIDIA GeForce RTX 4090
Active: 1
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0
Dimensions: {3440, 1440}
Position: {840, -1440}

Display #2
Device name: \\.\DISPLAY2
Device string: NVIDIA GeForce RTX 4090
Active: 1
Mirroring: 0
Modes pruned: 0
Primary: 4
Removable: 0
VGA compatible: 0
Dimensions: {5120, 1440}
Position: {0, 0}

Display #3
Device name: \\.\DISPLAY3
Device string: NVIDIA GeForce RTX 4090
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #4
Device name: \\.\DISPLAY4
Device string: NVIDIA GeForce RTX 4090
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #5
Device name: \\.\DISPLAY5
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #6
Device name: \\.\DISPLAY6
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #7
Device name: \\.\DISPLAY7
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #8
Device name: \\.\DISPLAY8
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #9
Device name: \\.\DISPLAY9
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #10
Device name: \\.\DISPLAY10
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #11
Device name: \\.\DISPLAY11
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #12
Device name: \\.\DISPLAY12
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #13
Device name: \\.\DISPLAY13
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #14
Device name: \\.\DISPLAY14
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #15
Device name: \\.\DISPLAY15
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #16
Device name: \\.\DISPLAY16
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #17
Device name: \\.\DISPLAY17
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #18
Device name: \\.\DISPLAY18
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #19
Device name: \\.\DISPLAY19
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #20
Device name: \\.\DISPLAY20
Device string: Parsec Virtual Display Adapter
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #21
Device name: \\.\DISPLAY21
Device string: Meta Virtual Monitor
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #22
Device name: \\.\DISPLAY22
Device string: Meta Virtual Monitor
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #23
Device name: \\.\DISPLAY23
Device string: Meta Virtual Monitor
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #24
Device name: \\.\DISPLAY24
Device string: Meta Virtual Monitor
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #25
Device name: \\.\DISPLAY25
Device string: Meta Virtual Monitor
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #26
Device name: \\.\DISPLAY26
Device string: Meta Virtual Monitor
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0

Display #27
Device name: \\.\DISPLAY27
Device string: Meta Virtual Monitor
Active: 0
Mirroring: 0
Modes pruned: 0
Primary: 0
Removable: 0
VGA compatible: 0
```

**Comment by rdlugosz** [comment]
Fixed! I wasn't using Parsec, so I uninstalled it out of curiosity & the GUI now works perfectly. Must have something to do with how the GUI interacts with the Parsec virtual display driver.

Note: I still have the Meta virtual displays listed and they do not seem to cause any issue.

**Comment by programmer2514** [comment]
Thank you for the information!

I did not know that applications like Parsec had this behavior, but I should be able to push a fix for it in the next few days.

**Comment by programmer2514** [comment]
Oddly, after setting up a test environment with Parsec and confirming I have all of the virtual displays, the GUI still works for me. Strange... @rdlugosz, if you re-install Parsec does the problem come back?

**Comment by programmer2514** [comment]
I have pushed a change to the DPEdit repo that should make inactive monitors invisible to DPEdit-GUI. In theory that should fix the issue.

**Comment by rdlugosz** [comment]
@programmer2514 I don't want to mess with Parsec any more at this point, but your fix seems reasonable to me, too. If not, someone will find this conversation in the future! :)
