### ISSUE TITLE
GUI version does not match windows display numbering (Dec 2023)

### ISSUE THREAD

**Issue by GDayvid** [programmer2514/DPEdit-GUI#3]
Hi there and thank you for the utility.

In my 3 monitor setup the GUI version does not match the identity of 2nd and 3rd monitors as reported. in Windows settings and Nvidia control panel.

![image](https://github.com/programmer2514/DPEdit/assets/153960950/7bcc7dec-5584-4cb9-9e6c-02cd724df15e)

**Comment by programmer2514** [comment]
This is actually intended behavior - Windows' display manager shows monitors in the order they were first plugged into the PC (when their IDs were added to the registry), whereas DPEdit enumerates them in the order which the GPU recognizes them. This is both much easier to do from a coding perspective and a better indicator of actual display order as seen by the BIOS.

**Comment by GDayvid** [comment]
Thank you, sorry to have raised a non-issue. Very kind of you to explain.
