### ISSUE TITLE
Showing that the version is 1.0.0.

### ISSUE THREAD

**Issue by SMN204** [programmer2514/DPEdit-GUI#5]
It keeps showing that the version is 1.0.0.
What is the correct way to reinstall the GUI ?

![1 0 0](https://github.com/user-attachments/assets/b7caf7d8-c99e-4cfd-8311-a870810e3d3d)

**Comment by programmer2514** [comment]
This was an error on my part - you should be able to update now. You may receive a prerequisites error after updating this time, since I changed the way that it works, but you can safely close/ignore it.
