### ISSUE TITLE
Error: "DPEdit failed to set display position!"

### ISSUE THREAD

**Issue by gsture** [programmer2514/DPEdit-GUI#6]
Windows version: 24H2
DEPEdit-GUI version: 1.1.2

On recent windows 11 versions i get an error when trying to set my display positions. This is a clean installation of windows, i tried to set display positions directly after installation.

![DPedit1](https://github.com/user-attachments/assets/d4359968-65b1-4f37-b31a-17b653330bbc)

**Comment by sjain882** [comment]
Having the same issue on Windows 10 22H2.

**Comment by programmer2514** [comment]
This issue should be fixed in v1.1.3
