### ISSUE TITLE
Some monitors slide away off screen with slight mouse movements & renderer breaks

### ISSUE THREAD

**Issue by sjain882** [programmer2514/DPEdit-GUI#7]
This seems to happen every time I use the program, not randomly. Not sure what logs / info I can provide.

The monitor that slides away is exactly the same as monitor 4 - Dell U2412M @ 1920x1200, 100% DPI, 60Hz.

Couldn't move monitor 5 (centre).

Monitor 6 is -1920,-15 (top-left).

Windows 10 22H2.

https://github.com/user-attachments/assets/8731515b-9760-41c4-9fa8-e2ce1a1548f2

![image](https://github.com/user-attachments/assets/2ec8fe3b-4326-45e6-8bf1-a43de64fc080)

**Comment by programmer2514** [comment]
This issue should be fixed in v1.1.3
